/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BillDetails: typeof import('./src/components/BillDetails.vue')['default']
    BookingsSection: typeof import('./src/components/sections/BookingsSection.vue')['default']
    BurgerButton: typeof import('./src/components/ui/BurgerButton.vue')['default']
    ButtonFX: typeof import('./src/components/ui/ButtonFX.vue')['default']
    ContactManager: typeof import('./src/components/ContactManager.vue')['default']
    DashboardCard: typeof import('./src/components/DashboardCard.vue')['default']
    DashboardContainer: typeof import('./src/components/layout/DashboardContainer.vue')['default']
    DashboardHeader: typeof import('./src/components/layout/DashboardHeader.vue')['default']
    DashboardLayout: typeof import('./src/components/layout/DashboardLayout.vue')['default']
    DashboardSidebar: typeof import('./src/components/layout/DashboardSidebar.vue')['default']
    DesktopMenu: typeof import('./src/components/navigation/DesktopMenu.vue')['default']
    DocumentViewer: typeof import('./src/components/DocumentViewer.vue')['default']
    EmailPopup: typeof import('./src/components/EmailPopup.vue')['default']
    EmergencyContacts: typeof import('./src/components/EmergencyContacts.vue')['default']
    EventDetails: typeof import('./src/components/EventDetails.vue')['default']
    FacilityBooking: typeof import('./src/components/FacilityBooking.vue')['default']
    GradientButton: typeof import('./src/components/ui/GradientButton.vue')['default']
    ImgNext: typeof import('./src/components/ui/ImgNext.vue')['default']
    KagiLogo: typeof import('./src/components/KagiLogo.vue')['default']
    KButton: typeof import('./src/components/core/KButton.vue')['default']
    KCard: typeof import('./src/components/core/KCard.vue')['default']
    KCheckbox: typeof import('./src/components/form/KCheckbox.vue')['default']
    KInput: typeof import('./src/components/form/KInput.vue')['default']
    KModal: typeof import('./src/components/core/KModal.vue')['default']
    KRadio: typeof import('./src/components/form/KRadio.vue')['default']
    KSelect: typeof import('./src/components/form/KSelect.vue')['default']
    KSwitch: typeof import('./src/components/form/KSwitch.vue')['default']
    KTable: typeof import('./src/components/core/KTable.vue')['default']
    KTextarea: typeof import('./src/components/form/KTextarea.vue')['default']
    KToast: typeof import('./src/components/core/KToast.vue')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    MaintenanceSection: typeof import('./src/components/sections/MaintenanceSection.vue')['default']
    MobileMenu: typeof import('./src/components/navigation/MobileMenu.vue')['default']
    ProfileSection: typeof import('./src/components/sections/ProfileSection.vue')['default']
    ProgressBar: typeof import('./src/components/ui/ProgressBar.vue')['default']
    SectionHeader: typeof import('./src/components/dashboard/SectionHeader.vue')['default']
    Spinner: typeof import('./src/components/ui/Spinner.vue')['default']
    StatCard: typeof import('./src/components/dashboard/StatCard.vue')['default']
    SVGCircle: typeof import('./src/components/ui/SVGCircle.vue')['default']
  }
}
